import type { Metadata } from "next";

import "./globals.css";
import Route from "@/component/Route";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-100 `}
      >
        <Route/>
        {children}
      </body>
    </html>
  );
}
